import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Register fonts (using built-in Helvetica for reliability)
const styles = StyleSheet.create({
  page: {
    padding: 72,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.6,
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 16,
  },
  date: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 16,
  },
  recipient: {
    fontSize: 11,
    marginBottom: 4,
    fontFamily: "Helvetica-Bold",
  },
  subject: {
    fontSize: 11,
    marginBottom: 16,
    fontFamily: "Helvetica-Bold",
  },
  body: {
    fontSize: 11,
    lineHeight: 1.7,
    textAlign: "justify",
  },
  paragraph: {
    marginBottom: 10,
  },
  footer: {
    marginTop: 32,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  disclaimer: {
    fontSize: 8,
    color: "#9ca3af",
    fontStyle: "italic",
    marginTop: 24,
  },
  branding: {
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 8,
  },
});

interface AppealPdfDocumentProps {
  recipient: string;
  subject: string;
  body: string;
  date: string;
}

export function AppealPdfDocument({
  recipient,
  subject,
  body,
  date,
}: AppealPdfDocumentProps) {
  // Split body into paragraphs for proper rendering
  const paragraphs = body.split("\n\n").filter((p) => p.trim().length > 0);

  return (
    <Document
      title={`Appeal Letter - ${subject}`}
      author="ClaimAppeal AI"
      subject={subject}
    >
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.date}>{date}</Text>
          <Text style={styles.recipient}>{recipient}</Text>
        </View>

        {/* Subject */}
        <Text style={styles.subject}>Re: {subject}</Text>

        {/* Body */}
        <View style={styles.body}>
          {paragraphs.map((para, i) => (
            <Text key={i} style={styles.paragraph}>
              {para.trim()}
            </Text>
          ))}
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.disclaimer}>
            This letter was drafted with the assistance of ClaimAppeal AI.
            All information should be reviewed for accuracy before submission.
            This document does not constitute legal or medical advice.
          </Text>
          <Text style={styles.branding}>
            Generated by ClaimAppeal AI · claimappeal.ai
          </Text>
        </View>
      </Page>
    </Document>
  );
}
